esphome:
  name: air-conditioner-remote
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1bd32c8898eebe4ec8c3142244803b5d"

wifi:
  ssid: "TP-Link_17C8"
  password: "abcd1234"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Conditioner-Remote"
    password: "nIyT3tCGSlOC"

captive_portal:

time:
  platform: homeassistant
  id: homeassistant_time
  
  # Example configuration entry
remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

climate:
  platform: climate_ir_lg
  name: "AC - Multi"
    

  

