esphome:
  name: dht
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "aa9a635382d629fde3f7039c48c88311"

wifi:
  ssid: "TP-Link_17C8"
  password: "abcd1234"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht Fallback Hotspot"
    password: "MSHaE0ReAAOA"

captive_portal:

sensor:
  - platform: dht
    model: dht22
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 15s