esphome:
  name: dht11
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "4ebd118fda1615ffdf65086fcb1dff67"

wifi:
  ssid: "wifi-name"
  password: "wifi-password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht11 Fallback Hotspot"
    password: "kQNBbnWUDOEX"

captive_portal:

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s